# Server configurations
server:
  host: "0.0.0.0"
  port: 8080
  outer_host: "localhost"

# Database credentials
database:
  user: "root"
  password: "root"
  dbName: "projectmanagement"
  host: "mysql"
  port: 3306