# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
env:
 LOGIN: ${{ secrets.DOCKER_LOGIN }}
 NAME: ${{ secrets.DOCKER_NAME }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: check current dir
        run: ls
      - name: Login to docker.io
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - name: Build image for user service
        run: |
          cd "Lab Work №5"/"Source Code"/user_service
          docker build --pull --rm -f build/package/run.Dockerfile -t $LOGIN/$NAME:run .
      - name: Build image for user database
        run: |
          cd "Lab Work №5"/"Source Code"/user_service
          docker build --pull --rm -f build/package/mysql.Dockerfile -t $LOGIN/$NAME:mysql .
      - name: Build image for meeting service
        run: |
          cd "Lab Work №5"/"Source Code"/meeting_service
          docker build --pull --rm -f build/package/run.Dockerfile -t $LOGIN/$NAME:run-meeting .
      - name: Build image for meeting database
        run: |
          cd "Lab Work №5"/"Source Code"/meeting_service
          docker build --pull --rm -f build/package/mysql.Dockerfile -t $LOGIN/$NAME:mysql-meeting .
      - name: Push all builded images to docker.io
        run: |
          docker push $LOGIN/$NAME:run
          docker push $LOGIN/$NAME:run-meeting
          docker push $LOGIN/$NAME:mysql
          docker push $LOGIN/$NAME:mysql-meeting
